openapi: 3.0.0
info:
  description: Serviço responsavel pelo envio de notificacoes em massa
  title: Pubsub Notification API
  contact: {}
  version: 1.0.0
paths:
  /api-products/routes/rules/scopes:
    get:
      tags:
        - API Products
      summary: Obter scopes permitidos em uma determinada rota
      parameters:
        - description: Nome da rota cadastrada o Kong. Esse nome é gerado pelo publisher
            de API Products no Kong, o Viveiro(u0).
          name: route
          in: query
          required: true
          schema:
            type: string
        - description: O ID do tenant é necessário para que o Platform Account filtre
            somente os scopes permitidos para aquele tenant.
          name: tenant
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Resposta de sucesso contendo um ou mais scopes permitidos na rota
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        "400":
          description: Falha de regra de negócio ao realizar a consulta
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                  - type: object
                    properties:
                      message:
                        type: string
        "500":
          description: Falha não identificada ao realizar a consulta
          content:
            application/json:
              schema:
                allOf:
                  - type: object
                  - type: object
                    properties:
                      message:
                        type: string
  